function [H,f] = calculateHf(Q,R,S,P,S1,S2,r,X0, Rs, u0)
%Vypočte parametry pro kvadratické programování z Q,R,P,S1,S2,r,X0, Rs
%
size_Q = size(Q);
N = size_Q(1);
Df=eye(N)-diag(ones(N-1,1),-1); % Diff matrix
Df0=[-1;zeros(N-1,1)];



%PRO TESTOVÁNÍ
%{
u_sm = 5*ones(size(Rs));
JN = (r-P*X0-S1*u_sm -S2*Rs)'*Q*(r-P*X0-S1*u_sm -S2*Rs)+R*u_sm + (Df*u_sm+Df0*u0)'*S*(Df*u_sm+Df0*u0)


JN = ...
+(r-P*X0-S2*Rs)'*Q*(r-P*X0-S2*Rs)...
+(r-P*X0-S2*Rs)'*Q*(-S1*u_sm)...
+(-S1*u_sm)'*Q*(r-P*X0-S2*Rs)...
+(-S1*u_sm)'*Q*-S1*u_sm...
+R*u_sm...
+u_sm'*Df'*S*Df*u_sm...
+2*(Df0*u0)'*S*Df*u_sm...
+(Df0*u0)'*S*(Df0*u0)

JN = ...
+(r-P*X0-S2*Rs)'*Q*(r-P*X0-S2*Rs)...
+2*(r-P*X0-S2*Rs)'*Q*(-S1*u_sm)...
+(-S1*u_sm)'*Q*-S1*u_sm...
+R*u_sm...
+u_sm'*Df'*S*Df*u_sm...
+2*(Df0*u0)'*S*Df*u_sm...
+(Df0*u0)'*S*(Df0*u0)

JN = ...
+(r-P*X0-S2*Rs)'*Q*(r-P*X0-S2*Rs)...
-2*(r-P*X0-S2*Rs)'*Q*S1*u_sm...
+u_sm'*S1'*Q*S1*u_sm...
+R*u_sm...
+u_sm'*Df'*S*Df*u_sm...
+2*(Df0*u0)'*S*Df*u_sm...
+(Df0*u0)'*S*(Df0*u0)

JN = ...
+(r-P*X0-S2*Rs)'*Q*(r-P*X0-S2*Rs)    +(Df0*u0)'*S*(Df0*u0)+...
+2*((R/2)-1*(r-P*X0-S2*Rs)'*Q*S1+(Df0*u0)'*S*Df)*u_sm...
+u_sm'*(S1'*Q*S1+Df'*S*Df)*u_sm 


j0=(r-P*X0-S2*Rs)'*Q*(r-P*X0-S2*Rs)    +(Df0*u0)'*S*(Df0*u0);
f= ((R/2)-1*(r-P*X0-S2*Rs)'*Q*S1+(Df0*u0)'*S*Df);
H=S1'*Q*S1+Df'*S*Df;

% quadratic form
JN = u_sm'*H*u_sm+2*f*u_sm+j0
%}

f= ((R/2)-1*(r-P*X0-S2*Rs)'*Q*S1+(Df0*u0)'*S*Df);
H=S1'*Q*S1+Df'*S*Df;

end

